Updating argocd login task

diff --git a/.tekton/tasks/sync-argocd-app.yaml b/.tekton/tasks/sync-argocd-app.yaml
--- a/.tekton/tasks/sync-argocd-app.yaml
+++ b/.tekton/tasks/sync-argocd-app.yaml
@@ -10,36 +10,34 @@ spec:
       type: string
       description: Title of the pull request which has been merged to be deployed on RHTAP staging environment
       default: ""
+  results:
+    - name: app-name
+      description: Name of the app to be synced
   workspaces:
-    - name: infra-deployment-git
+   - name: argocd-config
   steps:
     - name: argocd-app-sync
       image: quay.io/devtools_gitops/test_image:4.0.5
-      workingDir: $(workspaces.infra-deployment-git.path)
+      workingDir: $(workspaces.argocd-config.path)
+      env:
+        - name: PULL_REQUEST_TITLE
+          value: $(params.pull_request_title)
       script: |
-        #!/usr/bin/env python3
-        import subprocess
+        #!/usr/bin/env sh
+        set -u -o pipefail
 
-        cmd = "pip3 install pyyaml"
-        output = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
-        stdout, stderr = output.communicate()
+        chmod 0400 "$(pwd)/argocdconfig"
+        declare app_name=
+        for i in $(argocd app list --config "$(pwd)/argocdconfig"); do
+          app_name=$(echo $PULL_REQUEST_TITLE | grep -o "\b$i\b")
+          if [ -n $app_name ]; then
+            echo "trigger the deployment for $app_name"
+            argocd app sync $app_name --config "$(pwd)/argocdconfig"
+            echo $app_name | tee $(results.app-name.path)
+            break
+          fi
+        done
 
-        # Load param config versions
-        with open('argocd-staging-app.yaml') as f:
-          import yaml
-          app = yaml.safe_load(f)
-        
-        # Function to check if the element is present in pull-request-title
-        def contains_app(element):
-            return element in $(params.pull_request_title)
-
-        # Find the matching application
-        matched_app_name = next((element for element in app if contains_app(element)), None)
-
-        if matched_app_name:
-          app_name = ', '.join(matched_app_name)
-          echo "trigger the deployment"
-          argocd app sync app_name
-        else:
-          print("Either the app has not been added to staging yet or argocd-staging-app.yaml file does not have information of the app")
-
+        if [ -z $app_name ]; then
+          echo "app: $PULL_REQUEST_TITLE not found in the argocd"
+        fi
